### ISSUE TITLE
[DMP] Bug when merging

### ISSUE THREAD

**Issue by soloincc** [ilri/azizi-biorepository#3]
Throws an error while merging 2 sheets
![merging_bug](https://cloud.githubusercontent.com/assets/436245/7796045/e3005342-02e3-11e5-8cbc-99705a92c0ac.png)

**Comment by jasonrogena** [comment]
Fix pushed in commit ffbfb3df02834db452b18424a6e59321d0642d65. Check if works before I close the issue
